logback 1.3.11
1.4系ではテスト実行時にエラーになる
java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

(cherry picked from commit 0a4b16c06a8c7f29e1a4d6f39a94d357ad10ecea)